# NumPy

## Creating NumPy arrays using lists

#### Importing the library

In [1]:
import numpy as np

#### Creating a list and then converting it into an array of 1 dimension.

In [2]:
list1 = [11,23,34,56]

In [3]:
list1

[11, 23, 34, 56]

In [4]:
np.array(list1)

array([11, 23, 34, 56])

In [5]:
array1 = np.array(list1)

In [6]:
array1

array([11, 23, 34, 56])

#### Creating a list of list and converting it into an array of 2 dimensions.

In [7]:
list2 = [[11,22,33],[55,66,77],[88,99,100]]

In [8]:
np.array(list2)

array([[ 11,  22,  33],
       [ 55,  66,  77],
       [ 88,  99, 100]])

As seen above, there are two dimension i.e rows and columns. The dimension is also indicated with the number of brackets the array is enclosed in. There is one round bracket and a square bracket with encloses the array, therefore it is of 2 dimensions.

## Creating NumPy arrays using built-in methods

#### Creating using the arange method which is similar to python range. The arguments are start, stop and step values. The first value is 'start' and goes upto (stop-1) just like the range function.

In [9]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

#### Creating array of all zeros.

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

#### Creating array of all ones.

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

#### Creating array where the values are spaced equally in an interval. It takes the arguments: start, stop, number of values.

In [15]:
np.linspace(1,20,5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

As seen above, it returns 5 numbers in the interval 1 to 20 which are evenly spaced.

#### Creating identity matrix.

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Creating array with random numbers of the uniform distribution (0-1).

In [17]:
np.random.rand(3)

array([0.13772884, 0.06402546, 0.67401597])

In [18]:
np.random.rand(3,2)

array([[0.80041778, 0.86422877],
       [0.57487491, 0.97328796],
       [0.72863293, 0.29026413]])

#### Creating array with random numbers of the normal distribution (centered around 0).

In [19]:
np.random.randn(3)

array([-0.1291011 , -0.23886701, -1.07568397])

In [20]:
np.random.randn(4,2)

array([[-1.37516506,  0.40666943],
       [ 1.28101182, -0.09486107],
       [-0.11205889, -2.02424197],
       [ 0.81634793, -1.4006699 ]])

#### Creating array with random integers using randint() where the arguments to be passed are low, high and size. Low is inclusive and high is exclusive.

In [21]:
np.random.randint(1,50)

17

In [22]:
np.random.randint(1,50,5)

array([ 5, 12,  3, 48, 23])

## Attributes and methods of the NumPy array

In [23]:
arr1 = np.arange(10,35)

In [24]:
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34])

#### Reshape method to change the array into new shape.

In [25]:
arr1.reshape(5,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

Incase while reshaping the matrix is not filled then it will give an error. Make sure that the number of rows multiplied by the number of columns equals the number of elements in the array.

In [26]:
arr1.reshape(3,3)

ValueError: cannot reshape array of size 25 into shape (3,3)

#### Finding the maximum and minimum values in the array.

In [27]:
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34])

In [28]:
arr1.max()

34

In [29]:
arr1.min()

10

To know the index at which the max or min value is present, use argmax() or argmin().

In [30]:
arr1.argmax()

24

In [31]:
arr1.argmin()

0

#### shape() method to find the shape of the array.

In [32]:
arr1.shape

(25,)

This denotes that the array is 1-D with 25 elements.

In [33]:
arr2 = arr1.reshape(5,5)

In [34]:
arr2.shape

(5, 5)

This denotes that the array is 2-D and has 5 rows and 5 columns.

#### Finding the datatype of the elements in the array.

In [35]:
arr1.dtype

dtype('int32')

## Indexing and selecting elements in 1-D NumPy Array

In [36]:
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34])

#### Using the slicing notation to pick elements from the array.

In [37]:
arr1[3]

13

In [38]:
arr1[1:5]

array([11, 12, 13, 14])

#### Using slicing to change values in an array, i.e broadcasting.

In [39]:
arr1[1:5] = 50

In [40]:
arr1

array([10, 50, 50, 50, 50, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34])

Now lets slice the array and broadcast it. Notice how the sliced array will have changed values but also the original array.

In [41]:
arr2 = arr1[10:15]

In [42]:
arr2

array([20, 21, 22, 23, 24])

In [43]:
arr2[:] = 25

In [44]:
arr2

array([25, 25, 25, 25, 25])

In [45]:
arr1

array([10, 50, 50, 50, 50, 15, 16, 17, 18, 19, 25, 25, 25, 25, 25, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34])

To avoid this, make a copy of the array and then broadcast.

In [46]:
arr_copy = arr1.copy()

In [47]:
arr_copy

array([10, 50, 50, 50, 50, 15, 16, 17, 18, 19, 25, 25, 25, 25, 25, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34])

In [48]:
arr_copy[:] = 1

In [49]:
arr_copy

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1])

In [50]:
arr1

array([10, 50, 50, 50, 50, 15, 16, 17, 18, 19, 25, 25, 25, 25, 25, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34])

## Indexing and selecting elements in 2-D NumPy Array

In [51]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [52]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Indexing using brackets

For indexing, pass row value and then the column value.

In [53]:
arr2[0][1]

2

You can also use the below notation where the row and column value are written separated by a comma.

In [54]:
arr2[0,1]

2

#### Getting the sub part of a matrix.

To get the sub matrix, use slicing. In the below example, select rows o and 1 and columns 1 and 2.

In [56]:
arr2[:2,1:]

array([[2, 3],
       [5, 6]])

## Conditional selection using boolean array

In [57]:
arr1

array([10, 50, 50, 50, 50, 15, 16, 17, 18, 19, 25, 25, 25, 25, 25, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34])

In [59]:
bool_arr = arr1 > 20

In [60]:
bool_arr

array([False,  True,  True,  True,  True, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

#### Getting the values where the bollean value is True.

In [61]:
arr1[bool_arr]

array([50, 50, 50, 50, 25, 25, 25, 25, 25, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34])

In [64]:
arr1[arr1<20]

array([10, 15, 16, 17, 18, 19])

 ## Operations: Array with Array

In [67]:
arr3 = np.arange(0,5)

In [69]:
arr3

array([0, 1, 2, 3, 4])

#### Elementwise operations

In [68]:
arr3 + arr3

array([0, 2, 4, 6, 8])

In [70]:
arr3 - arr3

array([0, 0, 0, 0, 0])

In [71]:
arr3 * arr3

array([ 0,  1,  4,  9, 16])

## Operations: Array with Scalars

In [72]:
arr3

array([0, 1, 2, 3, 4])

In [73]:
arr3 + 5

array([5, 6, 7, 8, 9])

In [74]:
arr3 - 2

array([-2, -1,  0,  1,  2])

In [75]:
arr3 * 3

array([ 0,  3,  6,  9, 12])

In [76]:
arr3 / 6

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667])

In [80]:
arr3 ** 3

array([ 0,  1,  8, 27, 64], dtype=int32)

In python, 0/0 gives an error but in NumPy, when 0/0 is performed, it gives a warning and returns a NAN (Null) value.

In [77]:
arr3

array([0, 1, 2, 3, 4])

In [78]:
arr3/arr3

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.])

In [79]:
1/arr3

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ])

## NumPy array functions

#### Finding the square root of each element in array.

In [81]:
np.sqrt(arr3)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

#### Finding the exponential of each element in array.

In [82]:
np.exp(arr3)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

#### Finding the maximum of the array.

In [83]:
arr3.max()

4

#### Trigonometric functions

In [84]:
np.sin(arr3)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [86]:
np.cos(arr3)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

#### Logarithmic function

In [87]:
np.log(arr3)

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])